### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by JiweiTian** [bsinger98/CyberGridSim#1]
Hi,
I am very interested in this work. Can you share with me the paper?
Thank you very much.

Best,

**Comment by bsinger98** [comment]
Sure :)
The paper is called: "Shedding Light on Inconsistencies in Grid Cybersecurity: Disconnects and Recommendations"
and can be found: [https://www.briansinger.me/papers/sp23-grid.pdf](https://www.briansinger.me/papers/sp23-grid.pdf)

I will add the link to the README. Let me know if you have any questions

**Comment by JiweiTian** [comment]
Thank you very much.
